### ISSUE TITLE
% Done field

### ISSUE THREAD

**Issue by lublasco** [planio-gmbh/redmine_issue_field_visibility#8]
Hi,

"% Done" field is a built in field that can't be hidden with your plugin. Are there any plans to include it?

Thanks you very much for your useful plugin!

**Comment by jkraemer** [comment]
Including this field isn't as straightforward as the other fields since it needs special treatment (would have to return 0 instead of nil to not break calculations / validations in the Issue model), which is why it was left out in the first place. At the moment there are no plans to include it but if you want to give it a go I'll be happy to review / include a pull request.
